spring.application.name=JWT_Practices
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgrest/localhost:5233/spring
spring.datasource.password=123456
spring.datasource.username=postgrest
